### ISSUE TITLE
Added muscle names in python interface

### ISSUE THREAD

**Issue by ValentinAllard** [pyomeca/biorbd#12]

**Comment by pariterre** [comment]
Hi @ValentinAllard,
Because of architectural reasons, to get properties from a muscle, it must be down-casted into a specialized muscle model. Hence, the returned muscle from the function `model.muscleGroup(idxG).muscle(idxM)` is of type s2mMuscle, which is an abstract, which must be casted into, for instance into a thelen muscle model ( `m = biorbd.s2mMuscleHillTypeThelen(model.muscleGroup(idxG).muscle(idxM))` ). Thereafter, you can access all the feature, for instance to get the name you can do `m.name()`

Hope this help!
