### ISSUE TITLE
NoedeSegment method error

### ISSUE THREAD

**Issue by manu13008** [pyomeca/biorbd#161]
Hi guys,

First of all, thank you for this great tool that you have been developping ! I tried the testing file from your github and it works fine on my computer.

So I decided to go further and tried to develop my own model based on an old acquisition.

Everything works fine until these lines of code : 

`markersOverFrames = []`
`for i in range(markers.shape[2]) :`
`        markersOverFrames.append([biorbd.NodeSegment(m) for m in markers[:, :, i].T])`

I get this error message : 

TypeError: Wrong number or type of arguments for overloaded function 'new_NodeSegment'.
  Possible C/C++ prototypes are:
    biorbd::rigidbody::NodeSegment::NodeSegment()
    biorbd::rigidbody::NodeSegment::NodeSegment(biorbd::utils::Scalar const &,biorbd::utils::Scalar const &,biorbd::utils::Scalar const &)
    biorbd::rigidbody::NodeSegment::NodeSegment(biorbd::utils::Vector3d const &)
    biorbd::rigidbody::NodeSegment::NodeSegment(biorbd::utils::Scalar const &,biorbd::utils::Scalar const &,biorbd::utils::Scalar const &,biorbd::utils::String const &,biorbd::utils::String const &,bool,bool,biorbd::utils::String const &,int)
    biorbd::rigidbody::NodeSegment::NodeSegment(biorbd::utils::Vector3d const &,biorbd::utils::String const &,biorbd::utils::String const &,bool,bool,biorbd::utils::String const &,int)

Do you have insights of how to resolve it ?

Thanks for letting me know

regards

Emmanuel AYAD

**Comment by pariterre** [comment]
Dear @manu13008 

Thanks for giving biorbd a shot :)
The Python interface due to SWIG interfacing is something surprising. I am still working on the interface but it is a huge interface to work on!

The problem you describe is when SWIG can't recognize a type (because I did not tell it how :roll_eyes: ). Specifically for the Vectors3d, I haven't got it yet. But I should do it soon. What you have do "should" intuitively work (but is not ready yet). The work around is to declare each element individually (`biorbd.NodeSegment(m[0], m[1], m[2])`)

So here is a minimal example using you snippet:
```python
import numpy as np
import biorbd

# Load the model and create some data
biorbd_model = biorbd.Model(biorbd_model_path)
markers = np.random.random((3, biorbd_model.nbMarkers(), 100))

# Dispatch the data in markers over frame list
markersOverFrames = []
for i in range(markers.shape[2]):
    markersOverFrames.append([biorbd.NodeSegment(m[0], m[1], m[2]) for m in markers[:, :, i].T])

```

I'll try to fix that soon, Thanks for reporting :)

**Comment by pariterre** [comment]
Hi there!
I was going to fix this now, but apparently I fixed it already. 
So the snippet you wrote should work just fine!
