### ISSUE TITLE
[REVIEW] C++ Compiling Help 

### ISSUE THREAD

**Issue by abhishektha** [pyomeca/biorbd#174]
I'm assuming the CMakeLists.txt in the examples folder is supposed to help compile the example c++ scripts. 
When I try to run it, I get an error:
```
CMake Error at CMakeLists.txt:21 (add_dependencies):
  add_dependencies called with incorrect number of arguments
```
I think this is due to the $BIORBD_NAME variable not being defined. What is this variable supposed to represent, and what should I set it to? Should I also be defining the locations for the biorbd_LIBRARY and biorbd_INCLUDE_DIR in the CMakeLists.txt? And should I also be defining the locations for Eigen and rbdl includes? 

I alternatively tried compiling with g++, and put in the biorbd, Eigen, and rbdl include libraries in the command line. Unfortunately I got the error  "undefined reference to `biorbd::rigidbody::GeneralizedVelocity::~GeneralizedVelocity()'", repeated for multiple class:functions. Not sure if this an error on my end, or with how the class:functions are defined in biorbd. 

Sorry if some of these questions are basic, I'm a little rusty on compiling my c++ scripts!

For JOSS review https://github.com/openjournals/joss-reviews/issues/2562

**Comment by pariterre** [comment]
Hello @abhishektha !
Sorry for the confusion! Examples are indeed examples on how to use `biorbd` but not how to compile them per se. So you have nothing special to do. When you compile `biorbd` (the main library), there is an option BUILD_EXAMPLE that is automatically set to ON. If one wants to not build the examples, they can set it to OFF. Otherwise, it will automatically build them.

So bottom line, if you already build `biorbd`, you probably have the examples already built in your build folder (`$BUILD_FOLDER/examples/$BUILD_TYPE/  where $BUILD_TYPE is the selected optimisation (usually Release, Debug or RelWithDebInfo) )

The reason there is no actual example of how to use `biorbd` outside my framework is because it is the usual workflow of CMake. That is using the command `find_package(biorbd REQUIRED)` and then linking and adding the headers via `biorbd_LIBRARIES` and `biorbd_INCLUDE_DIR`)

I hope this helps!

**Comment by pariterre** [comment]
I added an actual example of how to link a code to an current install of biorbd. It made me found a bug in the cmake share.
Thanks for that!
See #175

**Comment by abhishektha** [comment]
Thanks for the update @pariterre . I can compile everything now and run some c++ examples!
