### ISSUE TITLE
[REVIEW] Fix reference on JOSS Paper

### ISSUE THREAD

**Issue by abhishektha** [pyomeca/biorbd#180]
I can't seem to find this article that you have in your references, do you have more information as to where it was presented? 

Desmyttere, G., Hajizadeh, M., Bleau, J., & Begon, M. (2019). Foot orthosis with add-onrearfoot posting can alter foot kinematics. In.

For JOSS Review https://github.com/openjournals/joss-reviews/issues/2562#

**Comment by pariterre** [comment]
Hi there!
That is an InProceedings from the ASB conference (https://www.researchgate.net/publication/335025832_Foot_orthosis_with_add-on_rearfoot_posting_can_alter_foot_kinematics) 
However, since, the paper has actually been publish, so I changed the reference for the actual paper! Thanks for noticing!

**Comment by pariterre** [comment]
(See #179 )
