### ISSUE TITLE
compute angular velocity around CoM

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/biorbd#257]
If this kind of feature already exist, please just point it to me.
Otherwise, I will think of a way to do that (ideally without doing AngMom/bodyInertia).

**Comment by pariterre** [comment]
What do you call angular velocity? Because as far as I am concerned a point such as CoM cannot have an angular velocity... If you talk about the segment angular velocity re-expressed at the CoM, then no, there is no such thing. That said, I may be wrong, but I feel that this value would be the exact same as the one at the origin of the segment

**Comment by yugiero** [comment]
Please be more specific at what angular velocity you are talking about. A segments' angular velocity around the total body CoM? A segments' angular velocity around its CoM? Also, it can be expressed in different coordinate systems, like the world frame (an inertial frame) or the local frame of a segment.

**Comment by EveCharbie** [comment]
*Sorry guys, that was more of a note to myself so that I don't forget to implement it in a near future.
But yes I can be mors specific : I want to know the whole body angular velocity (in the global reference frame) around its rotation point (being the whole body CoM in the case of aerial motions). So there is a way (like pariterre said) to compute it by summing the rotation of each segment reexpressed at the CoM. 
Note : The thing is that I am worried that it might be a way of computing it that is too similar to the way we compute angular momentum, but I did not look into it yet. (Like I said if it is the case, then AngMom/bodyInertia would be the answer).

**Comment by yugiero** [comment]
Ok I see. When I remember it correctly though, an angular velocity can only be defined for a rigid system. like a segment. For planar motion, for each mass point in the segment, the ratio of its linear velocity to its distance from rotation center is the same, so it has a single angular velocity omega = v/r. For a general 3D motion you can define three angular velocities, one around each axis of the chosen coordinate frame and write them into a vector. However, multibody systems are not rigid and so we can't define a single angular velocity for the whole body.
Of course, nobody prevents you from adding up the angular velocities of the segments around the same point, when they are also specified around the axes of the same coordinate system. With appropriate weighting, this actually makes physical sense. For example. weighting it with the masses of the segments gives you the orbital part of the total body angular momentum.
If it doesn't exist yet, it might be actually useful (also for my study) to implement a function that calculates the total body angular momentum around the total body CoM, something like
`np.sum(np.array([m_segm[i]*np.cross(r_sC_bC[i],v_sC_bC[i] + Rot[i] @ I_0[i] @ Rot[i].T @ omega[i] ]) for in range(nsegm))`
where

- r_sC_bC is the vector from body CoM to segm CoM
- v_sC_bC is the velocity of segment CoM relative to body CoM
- Rot is the rotation matrix which converts from the segments local frame into the global frame
- I_0 is the inertia matrix in the segments local frame
- omega is the angular velocity of the segment around its CoM in the global frame (the ones you wanted to add up)

I'm providing this detailed answer because this is actually a large part of my project.

**Comment by EveCharbie** [comment]
An angulam momentum function already exists it is provided by rbdl (you can call it like this in python m.angulamMomentum(Q, Qdot, updatekin)

**Comment by pariterre** [comment]
For completeness of @EveCharbie answer, there is also a segment angular moment that can be called:
`m.CalcSegmentsAngularMomentum(Q, Qdot, updateKin)` which returns a vector of angular momenta :)

**Comment by yugiero** [comment]
Does this function calculate the segments angular momentum around its CoM or around the total body CoM?

**Comment by pariterre** [comment]
Here is the signature of the function:
```c++
    ///
    /// \brief Calculate the segment center of mass angular momentum with respect to the global center of mass
    /// \param Q The generalized coordinates
    /// \param Qdot The generalized velocities
    /// \param updateKin If the kinematics of the model should be computed
    /// \return The segments center of mass angular momentum
    ///
    std::vector<utils::Vector3d> CalcSegmentsAngularMomentum (
        const GeneralizedCoordinates &Q,
        const GeneralizedVelocity &Qdot,
        bool updateKin);
```

**Comment by yugiero** [comment]
Ok, easy. Then those can just be vectorially added to get the total body angular momentum :)

**Comment by pariterre** [comment]
That is correct

**Comment by yugiero** [comment]
Actually, I'm not sure. If this is computed as `m_segm*np.cross(r_sC_bC,v_sC_bC)`, it is only the orbital part of the angular momentum. As the segments rotate around their own center of mass, they also have a spin component. For segments being far away from the body CoM, this contribution is probably very small, but if the body CoM is close to a segments CoM, the contribution can be large.

**Comment by yugiero** [comment]
I stumbled upon this [https://link.springer.com/article/10.1007/s10514-013-9341-4] , maybe "average spatial velocity" is what you mean?
