### ISSUE TITLE
Problem with bioviz

### ISSUE THREAD

**Issue by yugiero** [pyomeca/biorbd#259]
Hi, sorry for bothering again. I'm trying to use bioviz, but there seems to be an inconsistency between the visualization and the joint values on the left panel. I recorded a 3min video that explains my problem: [https://vimeo.com/675579200](url). Let me know which files you need.

**Comment by pariterre** [comment]
Hi there!
The color's order of axes in bioviz follows RGB, so X is Red, Y is Green and Z is Blue.

I suspect that the problem comes from the fact that your other software has a different order for the rotations. For instance, you declared the frontward axis in your bioMod as the Z and the 3rd rotation (we can see that from the left pane of bioviz. The order or rotation you chosed is XYZ). For the other software, it is a bit more subtle. While the order of rotation in the other software is also XYZ (we can see it at 2:00 in the video), I suspect the X and the Z axes are inversed based on their respective colors (X seems to be mediolateral in your bioMod while in the other software, it seems to be the frontward axis, and vice versa). Therefore, that would mean that you are applying the mediolateral rotations to the frontward (and vice versa) and that the order of rotation (expressed in you bioMod) should be ZYX to match the one from the other software. 
Please note that the same angles expressed in different orders do not represent the same position. You can refer to my paper "Can one angle be simply subtracted from another to determine range of motion in three-dimensional motion analysis?" if you are not familiar with this concept.

If I am right, that means the other software uses a left handed system of axes (which I have seen in the past for modelling software). If so, you may have to multiply one of the values by -1

**Comment by pariterre** [comment]
Hello again!

> That doesn't rule out your suspection, of course, but let's assume that the order of rotation XYZ in bioviz means the same as the RxRyRz option you spotted in Houdini.

The T-pose is not so much interesting here as all the rotations are set to 0. You should set the first rotation (whatever the axis is ti) of a segment to a random value on both software and compare if they perform the same motion anatomically speaking. If not, change the order in your bioMod until you get the exact same movement for all your axes. 
Then, do not care about the name of the axes, but their order (that is, if you do a 40°/60°/70° in one, do the same in the other. You should get the same result from that point

> However, I noticed something that might reveal the problem. In Houdini, the three rotation parameters rx, ry, rz refer to the rotation of the current segment's frame about its own three axes. In bioviz, by changing the sliders back and forth and observing which axis stays fixed in space, the current segment's frame shows the following weird behaviour:
    RotX or RotY rotates the frame around the parent's x or y axis respectively
    RotZ rotates the frame around its own z axis
The translations are all defined into the directions of the parent frame's axes.

This is the intended behavior, but you made a slight mistake of interpretation. The rotation are always around the axis of the segment. The first rotation, since there was nothing before, is similar to rotate about the parent. Then from the second rotation, it rotates about the previously rotated segment. So, if you perform a XYZ rotation, the first X rotation is performed, then the Y, about the new pose, and finally the Z. Since the X and the Z are the first and last, they "feel" more natural (it feels that the fist rotate about the parent, and the last feels it rotates about the rotated segment), while the second feels unnatural (it is called the floating axis, and cannot be easily interpreted, apart if you iteratively add the rotations.

**Comment by pariterre** [comment]
Can you make a video out of this just so I make sure bioviz actually behaves as it should? :)

**Comment by yugiero** [comment]
Hi, sorry for the late answer, after some struggle I think I've found the problem.
First off, bioviz uses intrinsic rotation angle definitions, so it is always rotating around the segments current frame. The rotation order should therefore be denoted as AB'C''. In contrast, Houdini specifies the rotation angles relative to the fixed parent frame's axes (extrinsic). As far as I know, to go from extrinsic to intrinsic rotation order, one only needs to invert the order, i.e. CBA=AB'C''. So as you suggested, if my rotation order in houdini is XYZ, I should choose ZY'X'' in bioviz. By doing this, I still don't see the right motion in bioviz.
The reason is because by changing the rotation order, it somehow also changes the assignment of axes names. For example, it then takes the first of the 6 dof per joint as the z rotation value, even though it is the x rotation value. See the video:
https://vimeo.com/677835815

**Comment by yugiero** [comment]
Okay, so the rotation parameter for example in the AddSegment function is not only used to define the rotation order, but also which dof are active at all. Makes sense :) Yes, this is a neat way to swap the axes of my input array. It works perfectly now, thanks!
